### ISSUE TITLE
Sale Order Class

### ISSUE THREAD

**Issue by Lungile-Mthombeni** [Raretag-za/mawa-flutter-package#241]
May you please add the endpoint to create a sale order
Create Sales Order:

POST: https://dev.api.app.mawa.co.za/sales-order

Sample Request:
{
	"customer": "1000000001",
	"deliveryDate": "2023-02-04",
	"items": [{
		"product": "23223",
		"quantity": "10"
	}, {
		"product": "SOAP",
		"quantity": "10",
                "unitPrice":"200.00"
	}]
}

Sample Response:
{
    "id": "402881c0861435750186143a83910002",
    "number": "0000000003",
    "type": "SALES-ORDER",
    "status": "NEW"
}

"id":"ff80808186359c22018635a67cd10000"

**Comment by sizakelemahlangu** [comment]
Working on it

**Comment by sizakelemahlangu** [comment]
The method has been created, it is awaiting approval. @mohaletebogo can you please review it for us

**Comment by sizakelemahlangu** [comment]
Method is ready
