### ISSUE TITLE
GET sale order

### ISSUE THREAD

**Issue by Lungile-Mthombeni** [Raretag-za/mawa-flutter-package#242]
May you please add the folllowing GET method 
/sales-order/{id}

**Comment by Lungile-Mthombeni** [comment]
GET to search on Sale Order
/sales-order
{
  "type": "string",
  "subtype": "string",
  "status": "string",
  "partnerFunction": "string",
  "partnerNo": "string"
}

**Comment by sizakelemahlangu** [comment]
Working on it

**Comment by sizakelemahlangu** [comment]
The endpoint is not working. Can you please log an issue on mawa-bes

**Comment by sizakelemahlangu** [comment]
The method for get sales order has been created and it is awaiting approval. @mohaletebogo can you please review it for us

**Comment by Lungile-Mthombeni** [comment]
Endpoint works now did create another sale order and ran the GET method it returns now

**Comment by sizakelemahlangu** [comment]
The method is ready
