### ISSUE TITLE
Create Invoice Table

### ISSUE THREAD

**Issue by SibonisoNcube** [Raretag-za/mawa-flutter-package#243]
Please create me an invoice class and add the following methods:

Create Invoice
POST: https://dev.api.app.mawa.co.za/invoice

Sample Request:
{
	"customer": "1000000001",
	"dueDate": "2023-02-04",
	"items": [{
		"product": "23223",
		"quantity": "10"
	}, {
		"product": "SOAP",
		"quantity": "10",
                "unitPrice":"200.00"
	}]
}

- Get all invoice 
GET: https://dev.api.app.mawa.co.za/invoice

-Get Specific
GET: https://dev.api.app.mawa.co.za/invoice/{id}

**Comment by sizakelemahlangu** [comment]
Method has been created, it is awaiting approval. @mohaletebogo can you please review it for us

**Comment by sizakelemahlangu** [comment]
Method is ready to be used
