### ISSUE TITLE
Get Invoice

### ISSUE THREAD

**Issue by SibonisoNcube** [Raretag-za/mawa-flutter-package#250]
Can you please create these methods under invoice class:
Get all invoice.
-https://dev.api.app.mawa.co.za/invoice

**Comment by SibonisoNcube** [comment]
and method for getting specific invoice. 
-https://dev.api.app.mawa.co.za/invoice/{id}

**Comment by sizakelemahlangu** [comment]
Methods awaiting approval

**Comment by sizakelemahlangu** [comment]
Methods are ready
