### ISSUE TITLE
Persons class

### ISSUE THREAD

**Issue by koketsomagagane1219** [Raretag-za/mawa-flutter-package#265]
can we please have a method in the class to get partners using their partner role, the method needs to receive the partner role as a parameter and return a list of partner(s) details with the relevant role

**Comment by sizakelemahlangu** [comment]
Can I please have the screenshot where you tested the endpoint

**Comment by sizakelemahlangu** [comment]
The method is awaiting approval

**Comment by sizakelemahlangu** [comment]
The method is ready
